# Generated by Django 3.0.8 on 2020-11-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.IntegerField()),
                ('file_no', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=255)),
                ('mob_no', models.CharField(max_length=11)),
                ('gtr', models.CharField(max_length=100)),
                ('gtr_mob_no', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abv', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.District')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('taluka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Taluka')),
            ],
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('agrmnt_date', models.DateField()),
                ('chasis_no', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('principle_amt', models.IntegerField()),
                ('intrest_rate', models.FloatField()),
                ('emi_amt', models.FloatField()),
                ('months', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Client')),
                ('vehical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Vehical')),
            ],
            options={
                'unique_together': {('reg_no', 'chasis_no', 'engine_no')},
            },
        ),
        migrations.CreateModel(
            name='Faliya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('village_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Village')),
            ],
        ),
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_amt', models.FloatField(default=0, null=True)),
                ('amt', models.FloatField(default=0, null=True)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(null=True)),
                ('receipt_no', models.CharField(max_length=20, null=True)),
                ('remarks', models.TextField(null=True)),
                ('penalty', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='faliya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Faliya'),
        ),
        migrations.AddField(
            model_name='client',
            name='firm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Firm'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('firm_id', 'challan_no', 'file_no')},
        ),
    ]
