# Generated by Django 3.0.8 on 2020-09-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='challan_no',
            field=models.IntegerField(unique=True, verbose_name='Challan Number'),
        ),
    ]
