# Generated by Django 3.0.8 on 2020-09-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20200917_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='challan_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='file_no',
            field=models.CharField(max_length=15),
        ),
    ]
