# Generated by Django 3.0.8 on 2020-09-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20200918_0410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('firm_id', 'challan_no', 'file_no')},
        ),
    ]
