# Generated by Django 3.0.8 on 2020-09-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20200918_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('agrmnt_date', models.DateField()),
                ('chasis_no', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('princple_amt', models.IntegerField()),
                ('interst_rate', models.FloatField()),
                ('emi_amt', models.FloatField()),
                ('months', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Client')),
                ('vehical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Vehical')),
            ],
            options={
                'unique_together': {('reg_no', 'chasis_no', 'engine_no')},
            },
        ),
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.FloatField()),
                ('due_date', models.DateField()),
                ('paid_data', models.DateField(null=True)),
                ('receipt_no', models.CharField(max_length=20, null=True)),
                ('remarks', models.TextField(null=True)),
                ('penalty', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Loan')),
            ],
        ),
    ]
