# Generated by Django 3.0.8 on 2020-09-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_emi_loan_vehical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='interst_rate',
            new_name='intrest_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='princple_amt',
            new_name='principle_amt',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='vehical_id',
            new_name='vehical',
        ),
    ]
