# Generated by Django 3.0.8 on 2020-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_auto_20200920_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emi',
            old_name='paid_data',
            new_name='paid_date',
        ),
        migrations.AlterField(
            model_name='emi',
            name='amt',
            field=models.FloatField(null=True),
        ),
    ]
