# Generated by Django 3.0.8 on 2020-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_auto_20201010_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='paid_date',
            field=models.DateField(default=0, null=True),
        ),
    ]
