# Generated by Django 3.0.8 on 2020-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_auto_20201010_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='amt',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
