from django.urls import path

from .views import address, views

app_name = 'loan'
urlpatterns = [
    path('', views.index, name='index'),
    path('create-district',
         address.DistrictCreateView.as_view(),
         name='create-district'),
    path('update-district/<int:pk>',
         address.DistrictUpdateView.as_view(),
         name='update-district'),
    path('list-district',
         address.DistrictListView.as_view(),
         name='list-district'),
    path('create-taluka',
         address.TalukaCreateView.as_view(),
         name='create-taluka'),
    path('update-taluka/<int:pk>',
         address.TalukaUpdateView.as_view(),
         name='update-taluka'),
    path('list-taluka',
         address.TalukaListView.as_view(),
         name='list-taluka'),
    path('create-village',
         address.VillageCreateView.as_view(),
         name='create-village'),
    path('update-village/<int:pk>',
         address.VillageUpdateView.as_view(),
         name='update-village'),
    path('list-village',
         address.VillageListView.as_view(),
         name='list-village'),
    path('create-faliya',
         address.FaliyaCreateView.as_view(),
         name='create-faliya'),
    path('update-faliya/<int:pk>',
         address.FaliyaUpadateView.as_view(),
         name='update-faliya'),
    path('list-faliya',
         address.FaliyaListView.as_view(),
         name='list-faliya'),
]
